### ISSUE TITLE
program exit code

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#295]
The following Python should set the program exit code
```py
import sys
if __name__ == "__main__":
    sys.exit(1)
```

Not surprising giving the voodoo underneath, the following sort of works
```py
if __name__ == "__main__":
    return 1
```

Except when the signature of `main` is wrong, like with Dart:
> Error: A non-null value must be returned since the return type 'int' doesn't allow null.

I'll work on this as part of the alternative to https://github.com/adsharma/py2many/pull/262 , which is in progress.

**Comment by adsharma** [comment]
This looks interesting for rust. https://www.joshmcguigan.com/blog/custom-exit-status-codes-rust/

That suggests a signature of:

```
pub fn main() -> Exit<io::Error> {...}
```

where the error is translated to an i32 elsewhere. It's possible that we'll want to use a more generic error vs io:Error.

The reason why having an Error type instead of i32 as return is important, because we'll need to deal with file IO and other functions where error propagation is much easier via `f.write("foo")?`.

**Comment by jayvdb** [comment]
Implemented in https://github.com/adsharma/py2many/pull/353
