### ISSUE TITLE
Question: tox testing target

### ISSUE THREAD

**Issue by PXshadow** [adsharma/py2many#311]
Hey I apologize if I'm missing something obvious. I've digged through the source code and can't seem to find any way to run the tests (preferably through tox) for only a single language (in my case golang). Thanks for any help on this, I'm very impressed thus far with the tooling, and speed of the compiler.

Also noob question, feel free not to answer but what are you supposed to do with all of the pregenerated coverage files?

**Comment by adsharma** [comment]
```
tox -e py38 -- -k go 
```

should run only the golang tests.

Re: coverage files

They give us a clue about how much of the transpiler code remains untested after running tox. @jayvdb  is the expert on the topic.

**Comment by jayvdb** [comment]
I am not sure what you mean by "pregenerated coverage files".

There is quite a lot of generated files emitted during the test invocation.  And there are `.coverage` files, which are in theory used by `pytest-cov`.

We havent been maintaining the `.gitignore` very well, but a lot of them should be listed there.

We also could change the test output directories so that it is easier to glob them in `.gitignore`.

**Comment by PXshadow** [comment]
Yeah that would be helpful to glob more things in ``.gitignore`` , thank you for the command, it is working quite well, I'll close the issue.
