### ISSUE TITLE
Overwrite cli flag

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#355]
Currently the cli will happy overwrite an existing transpiled file.

e.g.
`py2many.py --rust=1 /tmp/foo.py` will overwrite `/tmp/foo.rs`

The same occurs if `--outdir` is used.

And in directory mode, this can cause a "target language project build phase" to go haywire, as there may be some stale generated files in the directory, left over from a previous transpilation.

https://github.com/adsharma/py2many/pull/350#pullrequestreview-694194375 makes this even more troublesome, as it would overwrite the input file.

Often forced overwrite is a `--force` flag.  Sometimes a shortopt of `-f` is allowed.

**Comment by adsharma** [comment]
Yeah - force/-f or overwrite/-w are both fine.

I'm less worried about overwriting the target (foo.rs), since the person using the tool will likely understand that this is generated code. If they make handwritten modifications to the code, they'll probably use a revision control system or move it elsewhere.

It's when the source and target are the same file that the behavior is more surprising.

I was also thinking we could implement `--extension` flag to pick an alternate extension (e.g `py3`).

**Comment by jayvdb** [comment]
`--extension` is already "Build a python extension" ;-)

**Comment by adsharma** [comment]
Forgot about it. --suffix works?

**Comment by jayvdb** [comment]
I'm not seeing the use-case for it yet, but `--suffix` is very clear.

**Comment by adsharma** [comment]
> preventing overwrite by default

Yeah - that's my main concern. Even if --outdir is the default for tests, we will have a newbie trying `helloworld.py` and having them surprised the least is a good strategy.

We could do something like:

```
if filename.resolve() == output_path.resolve() and not args.force:
    print(f"Do you really want to overwrite {filename}? Use --force")
```
